#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.16
# In conjunction with Tcl version 8.6
#    Sep 06, 2018 10:17:50 AM -0300  platform: Windows NT

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import listar_salcomm_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Listar_SALCOMM (root)
    listar_salcomm_support.init(root, top)
    root.mainloop()

w = None
def create_Listar_SALCOMM(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Listar_SALCOMM (w)
    listar_salcomm_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Listar_SALCOMM():
    global w
    w.destroy()
    w = None


class Listar_SALCOMM:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = 'wheat'  # X11 color: #f5deb3
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {Courier New} -size 10 -weight normal -slant"  \
            " roman -underline 0 -overstrike 0"

        top.geometry("600x450+452+200")
        top.title("Listar SALCOMM")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.Button1 = Button(top)
        self.Button1.place(relx=0.78, rely=0.82, height=56, width=106)
        self.Button1.configure(activebackground="#f4bcb2")
        self.Button1.configure(activeforeground="black")
        self.Button1.configure(background="wheat")
        self.Button1.configure(command=listar_salcomm_support.quit)
        self.Button1.configure(compound="top")
        self.Button1.configure(disabledforeground="#b8a786")
        self.Button1.configure(font=font10)
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="wheat")
        self.Button1.configure(highlightcolor="black")
        self._img1 = PhotoImage(file="../../page/examples/button/stop.gif")
        self.Button1.configure(image=self._img1)
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Push to Quit''')






if __name__ == '__main__':
    vp_start_gui()



